//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GluonCS.LiveUavLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GluonCS.LiveUavLayer.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring.
        /// </summary>
        internal static string Acquiring {
            get {
                return ResourceManager.GetString("Acquiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new block.
        /// </summary>
        internal static string Add_new_block {
            get {
                return ResourceManager.GetString("Add_new_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Are_you_sure {
            get {
                return ResourceManager.GetString("Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the connection?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_close_the_connection {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_close_the_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autopilot OFF
        ///Manual mode.
        /// </summary>
        internal static string Autopilot_OFF {
            get {
                return ResourceManager.GetString("Autopilot_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autopilot ON.
        /// </summary>
        internal static string Autopilot_ON {
            get {
                return ResourceManager.GetString("Autopilot_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t synchronize with data that has not yet been received. 
        ///Please read the navigation data from the module first or perform a Write operation..
        /// </summary>
        internal static string cantsynchronize {
            get {
                return ResourceManager.GetString("cantsynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration not possible.
        /// </summary>
        internal static string Configuration_not_possible {
            get {
                return ResourceManager.GetString("Configuration_not_possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! ConnectionLost !.
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to insert the block at the first empty line?.
        /// </summary>
        internal static string Do_you_want_me_to_insert_the_block_at_the_first_empty_line {
            get {
                return ResourceManager.GetString("Do_you_want_me_to_insert_the_block_at_the_first_empty_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error synchronizing.
        /// </summary>
        internal static string Error_synchronizing {
            get {
                return ResourceManager.GetString("Error_synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight time.
        /// </summary>
        internal static string Flight_time {
            get {
                return ResourceManager.GetString("Flight_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting the new block at the selected position.
        /// </summary>
        internal static string Inserting_the_new_block_at_the_selected_position {
            get {
                return ResourceManager.GetString("Inserting_the_new_block_at_the_selected_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New survey block.
        /// </summary>
        internal static string New_survey_block {
            get {
                return ResourceManager.GetString("New_survey_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next WP.
        /// </summary>
        internal static string Next_WP {
            get {
                return ResourceManager.GetString("Next_WP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string Not_found {
            get {
                return ResourceManager.GetString("Not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open the gluon navigation/block file you wish to insert.
        /// </summary>
        internal static string open_the_gluon_navigationblock {
            get {
                return ResourceManager.GetString("open_the_gluon_navigationblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first connect to the gluonpilot.
        /// </summary>
        internal static string Please_first_connect_to_the_gluonpilot {
            get {
                return ResourceManager.GetString("Please_first_connect_to_the_gluonpilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no empty position detected. Please select the line where you want the block to be inserted and try again..
        /// </summary>
        internal static string Sorry_no_empty_position_detected {
            get {
                return ResourceManager.GetString("Sorry_no_empty_position_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilized manual
        ///RC mode.
        /// </summary>
        internal static string Stabilized_manual {
            get {
                return ResourceManager.GetString("Stabilized_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The block will be inserted at line nr.
        /// </summary>
        internal static string The_block_will_be_inserted_at_line_nr {
            get {
                return ResourceManager.GetString("The_block_will_be_inserted_at_line_nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already is a Survey block. It will be cleared..
        /// </summary>
        internal static string There_already_is_a_Survey_block_It_will_be_cleared {
            get {
                return ResourceManager.GetString("There_already_is_a_Survey_block_It_will_be_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when writing the navigation.
        /// </summary>
        internal static string There_was_an_error_when_writing_the_navigation {
            get {
                return ResourceManager.GetString("There_was_an_error_when_writing_the_navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all local waypoints &amp; script commands.
        /// </summary>
        internal static string This_will_delete_all_local_waypoints___script_commands {
            get {
                return ResourceManager.GetString("This will delete all local waypoints & script commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in block.
        /// </summary>
        internal static string Time_in_block {
            get {
                return ResourceManager.GetString("Time_in_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to WP.
        /// </summary>
        internal static string Time_to_WP {
            get {
                return ResourceManager.GetString("Time_to_WP", resourceCulture);
            }
        }
    }
}
